<?php

/**
 * @file
 * Functions to support theming in the Vox Test theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function vox_test_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function vox_test_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function vox_test_preprocess_node(&$variables) {

}
